spring:
  application:
    name: spring-cloud-eureka-client
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    #setting home-page-url
    status-page-url-path: https://${eureka.instance.hostName}/info
    health-check-url: https://${eureka.instance.hostName}/health
    home-page-url: https://${eureka.instance.hostName}/